spring :
  datasource:
    url: jdbc:mysql://localhost:3306/carRenter
    username: root
    password: 1234
  jpa :
    show-sql: true
    hibernate :
      ddl-auto : create
logging:
  level:
    org.springframework.security: trace

